# Generated by Django 5.1.6 on 2025-06-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key_1', models.CharField(max_length=255)),
                ('key_2', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Series'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book')], max_length=20)),
                ('source', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=100)),
                ('cover_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('planned', 'Planned'), ('dropped', 'Dropped'), ('on_hold', 'On Hold')], default='planned', max_length=20)),
                ('progress_main', models.PositiveIntegerField(default=0)),
                ('progress_secondary', models.PositiveIntegerField(blank=True, null=True)),
                ('total_main', models.PositiveIntegerField(blank=True, null=True)),
                ('total_secondary', models.PositiveIntegerField(blank=True, null=True)),
                ('personal_rating', models.PositiveIntegerField(blank=True, choices=[(1, 'Bad'), (2, 'Neutral'), (3, 'Good')], null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
