# Generated by Django 5.1.6 on 2025-06-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
