# Generated by Django 5.1.6 on 2025-06-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mediaitem_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(choices=[('tmdb', 'TMDB'), ('igdb', 'IGDB'), ('mal', 'MyAnimeList'), ('anilist', 'AniList')], max_length=100, unique=True),
        ),
    ]
