# Generated by Django 5.1.6 on 2025-06-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_apikey_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='banner_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='cast',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='related_titles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='release_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='seasons',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
