# Generated by Django 5.1.6 on 2025-06-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mediaitem_banner_url_mediaitem_cast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='screenshots',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
