# Generated by Django 5.1.6 on 2025-06-30 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mediaitem_screenshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
