# Generated by Django 5.1.6 on 2025-07-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mediaitem_last_updated_mediaitem_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('character', 'Character'), ('actor', 'Actor')], max_length=10)),
                ('position', models.PositiveIntegerField()),
            ],
        ),
    ]
