# Generated by Django 5.1.6 on 2025-07-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_favoriteperson'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediaitem',
            unique_together={('source', 'source_id', 'media_type')},
        ),
    ]
