# Generated by Django 5.1.6 on 2025-07-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_mediaitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='banner_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='release_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
