# Generated by Django 5.1.6 on 2025-07-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_mediaitem_banner_url_alter_mediaitem_cover_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('home', 'Home'), ('movies', 'Movies'), ('tvshows', 'TV Shows'), ('anime', 'Anime'), ('games', 'Games'), ('manga', 'Manga'), ('books', 'Books')], max_length=20, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
