# Generated by Django 5.1.6 on 2025-07-08 06:57

from django.db import migrations


def create_nav_items(apps, schema_editor):
    NavItem = apps.get_model('core', 'NavItem')
    default_items = [
        ("home", 1),
        ("movies", 2),
        ("tvshows", 3),
        ("anime", 4),
        ("games", 5),
        ("manga", 6),
        ("books", 7),
    ]
    for name, pos in default_items:
        NavItem.objects.create(name=name, visible=True, position=pos)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_navitem'),
    ]

    operations = [
        migrations.RunPython(create_nav_items),
    ]