# Generated by Django 5.1.6 on 2025-08-10 14:18

from django.db import migrations, models

def convert_old_ratings(apps, schema_editor):
    MediaItem = apps.get_model('core', 'MediaItem')
    mapping = {1: 1, 2: 50, 3: 100}
    for item in MediaItem.objects.all():
        if item.personal_rating in mapping:
            item.personal_rating = mapping[item.personal_rating]
            item.save(update_fields=['personal_rating'])

def create_default_settings(apps, schema_editor):
    AppSettings = apps.get_model('core', 'AppSettings')
    if not AppSettings.objects.exists():
        AppSettings.objects.create(rating_mode='faces')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_populate_nav_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_mode', models.CharField(
                    choices=[
                        ('faces', 'Faces'),
                        ('stars_5', '1–5 Stars'),
                        ('scale_10', '1–10'),
                        ('scale_100', '1–100')
                    ],
                    default='faces',
                    max_length=20
                )),
            ],
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='personal_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(convert_old_ratings),
        migrations.RunPython(create_default_settings),
    ]
