# Generated by Django 5.1.6 on 2025-09-06 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_appsettings_alter_mediaitem_personal_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='show_date_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='show_repeats_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('green', 'Green')], default='dark', max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='repeats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
