# Generated by Django 5.1.6 on 2025-09-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_appsettings_show_date_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='episodes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
