# Generated by Django 5.1.6 on 2025-09-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mediaitem_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='favorite_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
