# Generated by Django 5.1.6 on 2025-10-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mediaitem_favorite_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('brown', 'Brown'), ('green', 'Green')], default='dark', max_length=20),
        ),
    ]
