# Generated by Django 5.1.6 on 2025-10-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_appsettings_theme_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteperson',
            name='person_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
