# Generated by Django 5.1.6 on 2025-11-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_person_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Series'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('music', 'Music')], max_length=20),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='name',
            field=models.CharField(choices=[('home', 'Home'), ('movies', 'Movies'), ('tvshows', 'TV Shows'), ('anime', 'Anime'), ('games', 'Games'), ('manga', 'Manga'), ('books', 'Books'), ('music', 'Music')], max_length=20, unique=True),
        ),
    ]
