# Generated by Django 5.1.6

from django.db import migrations


def add_music_navitem(apps, schema_editor):
    NavItem = apps.get_model('core', 'NavItem')
    if not NavItem.objects.filter(name='music').exists():
        NavItem.objects.create(name='music', visible=True, position=8)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_mediaitem_media_type_alter_navitem_name'),
    ]

    operations = [
        migrations.RunPython(add_music_navitem),
    ]
