# Generated by Django 5.1.6 on 2026-01-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_music_navitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='name',
            field=models.CharField(choices=[('home', 'Home'), ('movies', 'Movies'), ('tvshows', 'TV Shows'), ('anime', 'Anime'), ('games', 'Games'), ('manga', 'Manga'), ('books', 'Books'), ('music', 'Music')], max_length=20),
        ),
    ]
