# Generated by Django 5.1.6 on 2026-03-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_navitem_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediaitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='provider_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
