# Generated by Django 5.1.6 on 2026-03-17 14:21

from django.db import migrations


def move_ids_to_json(apps, schema_editor):
    MediaItem = apps.get_model('core', 'MediaItem')
    
    for item in MediaItem.objects.all():
        if not item.provider_ids:
            item.provider_ids = {}

        if item.source and item.source_id:
            item.provider_ids[item.source] = str(item.source_id)
        
        item.save(update_fields=['provider_ids'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_mediaitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(move_ids_to_json),
    ]
