# Generated by Django 5.1.6 on 2026-03-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20260317_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='source_id',
        ),
    ]
