# Generated by Django 5.1.6 on 2026-05-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_mediaitem_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='creators',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
