# Generated by Django 5.1.6 on 2026-05-12 13:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_mediaitem_creators_mediaitem_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collection')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mediaitem')),
            ],
            options={
                'ordering': ['position', '-date_added'],
                'unique_together': {('collection', 'item')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='collections', through='core.CollectionItem', to='core.mediaitem'),
        ),
    ]
