# Generated by Django 5.1.6 on 2026-06-02 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_collection_collectionitem_collection_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('notify', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('recurring_group', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.mediaitem')),
            ],
        ),
    ]
