# Generated by Django 5.1.6 on 2026-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='calendar_last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
