# Generated by Django 5.1.6 on 2026-06-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_mediaitem_calendar_last_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='show_collections_field',
            field=models.BooleanField(default=False),
        ),
    ]
