# Generated by Django 5.1.6 on 2026-06-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_appsettings_show_collections_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='cal_sync_ongoing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='cal_sync_planned',
            field=models.BooleanField(default=False),
        ),
    ]
