# Generated by Django 5.1.6 on 2026-06-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_appsettings_cal_sync_ongoing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='dismissed_system_notifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
