# Generated by Django 5.1.6 on 2026-07-11 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_appsettings_dismissed_system_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('activity_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_spoiler', models.BooleanField(default=False)),
                ('progress_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('progress_start', models.PositiveIntegerField(blank=True, null=True)),
                ('progress_end', models.PositiveIntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.mediaitem')),
            ],
            options={
                'ordering': ['-activity_date', '-date_added'],
            },
        ),
    ]
