# Generated by Django 5.1.6 on 2026-07-25 18:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_mediaitemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='details_sections_order',
            field=models.JSONField(blank=True, default=core.models.AppSettings.default_details_sections_order),
        ),
    ]
