# Generated by Django 5.1.6 on 2026-07-25 20:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_appsettings_details_sections_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('position', models.PositiveIntegerField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_date', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_videos', to='core.mediaitem')),
            ],
            options={
                'ordering': ['-is_favorite', 'position', 'date_added'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('is_full_url', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_date', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_screenshots', to='core.mediaitem')),
            ],
            options={
                'ordering': ['-is_favorite', 'position', 'date_added'],
            },
        ),
    ]
