# Generated by Django 5.1.6 on 2026-09-26 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20260725_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteperson',
            name='crew_credits',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoriteperson',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='favoriteperson',
            name='directed',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoriteperson',
            name='known_for',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoriteperson',
            name='produced',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoriteperson',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MediaPersonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_role', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mediaitem')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.favoriteperson')),
            ],
            options={
                'ordering': ['-date_added'],
                'unique_together': {('item', 'person', 'media_role')},
            },
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='assigned_people',
            field=models.ManyToManyField(blank=True, related_name='assigned_media', through='core.MediaPersonLink', to='core.favoriteperson'),
        ),
    ]
